# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160226_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
